### Lab 09 - Direct Methods for Solving Linear Systems

# Matrix Inversion method

In [3]:
import numpy as np

A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

A_inv = np.linalg.inv(A)

In [4]:
print(A_inv)

[[ 0.4 -0.2]
 [-0.2  0.6]]


In [5]:
print(np.dot(A_inv, b))

[2. 3.]


# Gaussian Elimination Method

This method transforms the system of equations into an upper triangular matrix from which solution can be obtained via back-substitution. The augmented matrix [A | b]

In [6]:
b.reshape(-1, 1)

array([[9],
       [8]])

In [7]:
np.hstack((A, b.reshape(-1, 1)))

array([[3, 1, 9],
       [1, 2, 8]])

In [8]:
def gaussian_elimination(A, b):
    n = len(b)

    Ab = np.hstack([A, b.reshape(-1, 1)])

    print(Ab[0, 0])


In [9]:
A = np.array([[3, 1], [1, 2]], dtype=float)
b = np.array([9, 8], dtype=float)

# Solve the system using Gaussian Elimination
x = gaussian_elimination(A, b)
print("Solution x:", x)

3.0
Solution x: None


In [10]:
def gauss_elimination(A, b):
    n = len(b)

    Ab = np.hstack([A, b.reshape(-1, 1)])


    for i in range(n):
        pivot = Ab[i, i]
        if pivot == 0:
            raise ValueError("Cannot proceed with gaussian method!")
        
        Ab[i] = Ab[i] / pivot

        for j in range(i + 1, n):
            scale = Ab[j, i]
            Ab[j] = Ab[j] - scale * Ab[i]

    xs = np.zeros(n)
    for i in range(n - 1, -1, -1):
        xs[i] = Ab[i, -1] - np.dot(Ab[i, i+1:n], xs[i+1:])


    return xs
        
        



In [11]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8], dtype=float)

print(gauss_elimination(A, b))

[2. 3.]


In [12]:
def gauss_elim(A, b):
    n = len(b)


    Ab = np.hstack([A, b.reshape(-1, 1)])


    for i in range(n):
        pivot = Ab[i, i]

        if pivot == 0:
            raise ValueError("Ah!!!")
        
        Ab[i] = Ab[i] / pivot


        for j in range(i + 1, n):
            scale = Ab[j, i]
            Ab[j] = Ab[j] - scale * Ab[i]

        xs = np.zeros(n)

    for i in range(n - 1, -1, -1):
        xs[i] = Ab[i,-1] - np.dot(Ab[i, i+1:n], xs[i+1:])

    return xs
    

In [13]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8], dtype=float)

print(gauss_elim(A, b))

[2. 3.]


## Gaussian Elimination with Backward Substitution (Without Pivoting)

In [17]:
# your code here
def gauss_elim_no_pivot(A, b):
    n = len(b)

    Ab = np.hstack([A, b.reshape(-1, 1)])

    for i in range(n):
        for j in range(i + 1, n):
            factor = Ab[j, i] / Ab[i, i]
            Ab[j] = Ab[j] - factor * Ab[i]

    
    # Backward substituion
    xs = np.zeros(n)
    for i in range(n - 1, -1, -1):
        xs[i] = (Ab[i, - 1] - np.dot(Ab[i, i + 1:n], xs[i+1:])) / Ab[i, i]

    return xs

# Example system of equations
A = np.array([[3, 1, 2], [1, 2, 3], [2, 1, 3]], dtype=float)
b = np.array([9, 8, 7], dtype=float)

# Solve the system using Gaussian elimination (no pivoting)
x = gauss_elim_no_pivot(A, b)
print("Solution x:", x)


Solution x: [2. 3. 0.]


### LU Decomposition

In [18]:
def lu_decomposition(A, b):
    n = len(b)

    Ab = np.hstack([A, b.reshape(-1, 1)])

    L = np.zeros_like(A)

    for i in range(n):
        for j in range(i + 1, n):
            factor = Ab[j, i] / Ab[i, i]
            Ab[j] = Ab[j] - factor * Ab[i]
            L[j, i] = factor # For Lower Triangular Matrix


    return L, Ab


In [22]:
A = np.array([[2, 4, 3],
              [-4, -7, -5],
              [6, 8, 2],
              [4, 9, -2]])
b =np.array([5, -8, 9, 14])

l, u = lu_decomposition(A, b)

In [23]:
print(l)
print(u)

[[ 0  0  0]
 [-2  0  0]
 [ 3 -4  0]
 [ 2  1  3]]
[[ 2  4  3  5]
 [ 0  1  1  2]
 [ 0  0 -3  2]
 [ 0  0  0 -4]]
