### Lab 09 - Direct Methods for Solving Linear Systems

# Matrix Inversion method

In [114]:
import numpy as np

A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

A_inv = np.linalg.inv(A)

In [115]:
print(A_inv)

[[ 0.4 -0.2]
 [-0.2  0.6]]


In [116]:
print(np.dot(A_inv, b))

[2. 3.]


# Gaussian Elimination Method

This method transforms the system of equations into an upper triangular matrix from which solution can be obtained via back-substitution. The augmented matrix [A | b]

In [117]:
b.reshape(-1, 1)

array([[9],
       [8]])

In [118]:
np.hstack((A, b.reshape(-1, 1)))

array([[3, 1, 9],
       [1, 2, 8]])

In [119]:
def gaussian_elimination(A, b):
    n = len(b)

    Ab = np.hstack([A, b.reshape(-1, 1)])

    print(Ab[0, 0])


In [120]:
A = np.array([[3, 1], [1, 2]], dtype=float)
b = np.array([9, 8], dtype=float)

# Solve the system using Gaussian Elimination
x = gaussian_elimination(A, b)
print("Solution x:", x)

3.0
Solution x: None


In [121]:
def gauss_elimination(A, b):
    n = len(b)

    Ab = np.hstack([A, b.reshape(-1, 1)])


    for i in range(n):
        pivot = Ab[i, i]
        if pivot == 0:
            raise ValueError("Cannot proceed with gaussian method!")
        
        Ab[i] = Ab[i] / pivot

        for j in range(i + 1, n):
            scale = Ab[j, i]
            Ab[j] = Ab[j] - scale * Ab[i]

    xs = np.zeros(n)
    for i in range(n - 1, -1, -1):
        xs[i] = Ab[i, -1] - np.dot(Ab[i, i+1:n], xs[i+1:])


    return xs
        
        



In [122]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8], dtype=float)

print(gauss_elimination(A, b))

[2. 3.]


In [123]:
def gauss_elim(A, b):
    n = len(b)


    Ab = np.hstack([A, b.reshape(-1, 1)])


    for i in range(n):
        pivot = Ab[i, i]

        if pivot == 0:
            raise ValueError("Ah!!!")
        
        Ab[i] = Ab[i] / pivot


        for j in range(i + 1, n):
            scale = Ab[j, i]
            Ab[j] = Ab[j] - scale * Ab[i]

        xs = np.zeros(n)

    for i in range(n - 1, -1, -1):
        xs[i] = Ab[i,-1] - np.dot(Ab[i, i+1:n], xs[i+1:])

    return xs
    

In [124]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8], dtype=float)

print(gauss_elim(A, b))

[2. 3.]


## Gaussian Elimination with Backward Substitution (Without Pivoting)

In [125]:
# your code here
def gauss_elim_no_pivot(A, b):
    n = len(b)

    Ab = np.hstack([A, b.reshape(-1, 1)])

    for i in range(n):
        for j in range(i + 1, n):
            factor = Ab[j, i] / Ab[i, i]
            Ab[j] = Ab[j] - factor * Ab[i]

    
    # Backward substituion
    xs = np.zeros(n)
    for i in range(n - 1, -1, -1):
        xs[i] = (Ab[i, - 1] - np.dot(Ab[i, i + 1:n], xs[i+1:])) / Ab[i, i]

    return xs

# Example system of equations
A = np.array([[3, 1, 2], [1, 2, 3], [2, 1, 3]], dtype=float)
b = np.array([9, 8, 7], dtype=float)

# Solve the system using Gaussian elimination (no pivoting)
x = gauss_elim_no_pivot(A, b)
print("Solution x:", x)


Solution x: [2. 3. 0.]


### LU Decomposition

In [126]:
def lu_decomposition(A):
    n = len(A)
    L = np.zeros_like(A)

    # Using Gaussian Elimination result in an upper triangular matrix
    # Meanwhile the factors form the lower triangular matrix,
    # Thus we can store them in L
    for i in range(n):
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j] = A[j] - factor * A[i]
            L[j, i] = factor # For Lower Triangular Matrix

    np.fill_diagonal(L, 1)
    return L, A


In [127]:
def forward_substitution(L, b):
    n = len(b)
    y = np.zeros_like(b, dtype=float)
    
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    
    return y

def backward_substitution(U, y):

    n = len(y)
    x = np.zeros_like(y, dtype=float)
    
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    
    return x

In [128]:
def solve_system(A, b):
    """
    Solve the system of linear equations Ax = b using LU decomposition.
    """
    # Step 1: Perform LU decomposition
    L, U = lu_decomposition(A)
    
    # Step 2: Solve Ly = b
    y = forward_substitution(L, b)
    
    # Step 3: Solve Ux = y
    x = backward_substitution(U, y)
    
    return x


A = np.array([[4, 3], [6, 3]], dtype=float)
b = np.array([10, 12], dtype=float)

x = solve_system(A, b)

print("Solution vector x:")
print(x)

Solution vector x:
[1. 2.]
